import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Outfit} from 'next/font/google'
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner";
import { dark, shadesOfPurple } from "@clerk/themes";


export const metadata = {
  title: "Brain-AI",
  description: "Generated by create next app",
};

const outfit=Outfit({subsets:['latin']});
export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark,
    }}>
    <html lang="en"  suppressHydrationWarning>
      <body
        className={outfit.className}
      >
        <Provider>
        {children}
        </Provider>
        <Toaster/>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
